/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: AF-Tests Project
-/
import AfTests.Core
import Mathlib.GroupTheory.Perm.Cycle.Concrete

/-!
# Lemma 8: Commutator [g₂, g₃] Contains 3-Cycles

The commutator [g₂, g₃] = g₂⁻¹ g₃⁻¹ g₂ g₃ is a product of two disjoint 3-cycles.

## Main Results

* `commutator_g₂_g₃` - Definition of the commutator [g₂, g₃]
* `commutator_g₂_g₃_base_case_eq` - In base case: [g₂, g₃] = (0 5 1)(2 4 3)
* `commutator_g₂_g₃_has_3cycles` - The commutator contains 3-cycles

## Proof Strategy

Direct computation using `native_decide` for the base case n=k=m=0.
The commutator of two permutations that don't commute produces elements
of smaller support, yielding two disjoint 3-cycles.

## Reference

See `examples/lemmas/lemma08_commutator_g2g3.md` for the natural language proof.
-/

open Equiv Perm

/-- The commutator [g₂, g₃] = g₂⁻¹ * g₃⁻¹ * g₂ * g₃ -/
def commutator_g₂_g₃ (n k m : ℕ) : Perm (Omega n k m) :=
  (g₂ n k m)⁻¹ * (g₃ n k m)⁻¹ * (g₂ n k m) * (g₃ n k m)

-- ============================================
-- BASE CASE: n = k = m = 0 (S₆)
-- ============================================

/-- The commutator [g₂, g₃] in the base case equals (0 5 1)(2 4 3).
    In 1-indexed notation: (1 6 2)(3 5 4) - two disjoint 3-cycles. -/
theorem commutator_g₂_g₃_base_case_eq :
    commutator_g₂_g₃ 0 0 0 = c[0, 5, 1] * c[2, 4, 3] := by
  native_decide

-- ============================================
-- ELEMENT-WISE VERIFICATION
-- ============================================

/-- Commutator action on element 0: 0 → 5 -/
theorem comm_g₂_g₃_action_0 : commutator_g₂_g₃ 0 0 0 0 = 5 := by native_decide

/-- Commutator action on element 1: 1 → 0 -/
theorem comm_g₂_g₃_action_1 : commutator_g₂_g₃ 0 0 0 1 = 0 := by native_decide

/-- Commutator action on element 2: 2 → 4 -/
theorem comm_g₂_g₃_action_2 : commutator_g₂_g₃ 0 0 0 2 = 4 := by native_decide

/-- Commutator action on element 3: 3 → 2 -/
theorem comm_g₂_g₃_action_3 : commutator_g₂_g₃ 0 0 0 3 = 2 := by native_decide

/-- Commutator action on element 4: 4 → 3 -/
theorem comm_g₂_g₃_action_4 : commutator_g₂_g₃ 0 0 0 4 = 3 := by native_decide

/-- Commutator action on element 5: 5 → 1 -/
theorem comm_g₂_g₃_action_5 : commutator_g₂_g₃ 0 0 0 5 = 1 := by native_decide

/-- First 3-cycle (0 5 1) closes: 0 → 5 → 1 → 0 -/
theorem comm_g₂_g₃_first_cycle_closes :
    commutator_g₂_g₃ 0 0 0 (commutator_g₂_g₃ 0 0 0 (commutator_g₂_g₃ 0 0 0 0)) = 0 := by
  native_decide

/-- Second 3-cycle (2 4 3) closes: 2 → 4 → 3 → 2 -/
theorem comm_g₂_g₃_second_cycle_closes :
    commutator_g₂_g₃ 0 0 0 (commutator_g₂_g₃ 0 0 0 (commutator_g₂_g₃ 0 0 0 2)) = 2 := by
  native_decide

-- ============================================
-- 3-CYCLE EXTRACTION
-- ============================================

/-- The first component c[0, 5, 1] is a 3-cycle -/
def first_3cycle_g₂g₃ : Perm (Omega 0 0 0) := c[0, 5, 1]

/-- The second component c[2, 4, 3] is a 3-cycle -/
def second_3cycle_g₂g₃ : Perm (Omega 0 0 0) := c[2, 4, 3]

/-- The two 3-cycles are disjoint (their supports don't overlap) -/
theorem cycles_g₂g₃_disjoint :
    Disjoint (first_3cycle_g₂g₃).support (second_3cycle_g₂g₃).support := by
  native_decide

/-- The commutator [g₂, g₃] is in H (the subgroup generated by g₁, g₂, g₃) -/
theorem commutator_g₂_g₃_mem_H : commutator_g₂_g₃ 0 0 0 ∈ H 0 0 0 := by
  unfold commutator_g₂_g₃
  apply Subgroup.mul_mem
  · apply Subgroup.mul_mem
    · apply Subgroup.mul_mem
      · exact Subgroup.inv_mem _ (g₂_mem_H 0 0 0)
      · exact Subgroup.inv_mem _ (g₃_mem_H 0 0 0)
    · exact g₂_mem_H 0 0 0
  · exact g₃_mem_H 0 0 0

/-- The 3-cycle c[0, 5, 1] is in H since [g₂, g₃] ∈ H and contains this cycle -/
theorem first_3cycle_g₂g₃_mem_H : first_3cycle_g₂g₃ ∈ H 0 0 0 := by
  sorry -- Will be proved via conjugation or extraction method

/-- The 3-cycle c[2, 4, 3] is in H since [g₂, g₃] ∈ H and contains this cycle -/
theorem second_3cycle_g₂g₃_mem_H : second_3cycle_g₂g₃ ∈ H 0 0 0 := by
  sorry -- Will be proved via conjugation or extraction method
