/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: AF-Tests Project
-/
import AfTests.Core
import Mathlib.GroupTheory.Perm.Cycle.Concrete

/-!
# Lemma 7: Commutator [g₁, g₃] Contains 3-Cycles

The commutator [g₁, g₃] = g₁⁻¹ g₃⁻¹ g₁ g₃ is a product of two disjoint 3-cycles.

## Main Results

* `commutator_g₁_g₃` - Definition of the commutator [g₁, g₃]
* `commutator_g₁_g₃_base_case_eq` - In base case: [g₁, g₃] = (0 4 5)(1 2 3)
* `commutator_g₁_g₃_has_3cycles` - The commutator contains 3-cycles

## Proof Strategy

Direct computation using `native_decide` for the base case n=k=m=0.
The commutator of two permutations that don't commute produces elements
of smaller support, yielding two disjoint 3-cycles.

## Reference

See `examples/lemmas/lemma07_commutator_g1g3.md` for the natural language proof.
-/

open Equiv Perm

/-- The commutator [g₁, g₃] = g₁⁻¹ * g₃⁻¹ * g₁ * g₃ -/
def commutator_g₁_g₃ (n k m : ℕ) : Perm (Omega n k m) :=
  (g₁ n k m)⁻¹ * (g₃ n k m)⁻¹ * (g₁ n k m) * (g₃ n k m)

-- ============================================
-- BASE CASE: n = k = m = 0 (S₆)
-- ============================================

/-- The commutator [g₁, g₃] in the base case equals (0 4 5)(1 2 3).
    In 1-indexed notation: (1 5 6)(2 3 4) - two disjoint 3-cycles. -/
theorem commutator_g₁_g₃_base_case_eq :
    commutator_g₁_g₃ 0 0 0 = c[0, 4, 5] * c[1, 2, 3] := by
  native_decide

-- ============================================
-- ELEMENT-WISE VERIFICATION
-- ============================================

/-- Commutator action on element 0: 0 → 4 -/
theorem comm_g₁_g₃_action_0 : commutator_g₁_g₃ 0 0 0 0 = 4 := by native_decide

/-- Commutator action on element 1: 1 → 2 -/
theorem comm_g₁_g₃_action_1 : commutator_g₁_g₃ 0 0 0 1 = 2 := by native_decide

/-- Commutator action on element 2: 2 → 3 -/
theorem comm_g₁_g₃_action_2 : commutator_g₁_g₃ 0 0 0 2 = 3 := by native_decide

/-- Commutator action on element 3: 3 → 1 -/
theorem comm_g₁_g₃_action_3 : commutator_g₁_g₃ 0 0 0 3 = 1 := by native_decide

/-- Commutator action on element 4: 4 → 5 -/
theorem comm_g₁_g₃_action_4 : commutator_g₁_g₃ 0 0 0 4 = 5 := by native_decide

/-- Commutator action on element 5: 5 → 0 -/
theorem comm_g₁_g₃_action_5 : commutator_g₁_g₃ 0 0 0 5 = 0 := by native_decide

/-- First 3-cycle (0 4 5) closes: 0 → 4 → 5 → 0 -/
theorem comm_g₁_g₃_first_cycle_closes :
    commutator_g₁_g₃ 0 0 0 (commutator_g₁_g₃ 0 0 0 (commutator_g₁_g₃ 0 0 0 0)) = 0 := by
  native_decide

/-- Second 3-cycle (1 2 3) closes: 1 → 2 → 3 → 1 -/
theorem comm_g₁_g₃_second_cycle_closes :
    commutator_g₁_g₃ 0 0 0 (commutator_g₁_g₃ 0 0 0 (commutator_g₁_g₃ 0 0 0 1)) = 1 := by
  native_decide

-- ============================================
-- 3-CYCLE EXTRACTION
-- ============================================

/-- The first component c[0, 4, 5] is a 3-cycle -/
def first_3cycle_g₁g₃ : Perm (Omega 0 0 0) := c[0, 4, 5]

/-- The second component c[1, 2, 3] is a 3-cycle -/
def second_3cycle_g₁g₃ : Perm (Omega 0 0 0) := c[1, 2, 3]

/-- The two 3-cycles are disjoint (their supports don't overlap) -/
theorem cycles_g₁g₃_disjoint :
    Disjoint (first_3cycle_g₁g₃).support (second_3cycle_g₁g₃).support := by
  native_decide

/-- The commutator [g₁, g₃] is in H (the subgroup generated by g₁, g₂, g₃) -/
theorem commutator_g₁_g₃_mem_H : commutator_g₁_g₃ 0 0 0 ∈ H 0 0 0 := by
  unfold commutator_g₁_g₃
  apply Subgroup.mul_mem
  · apply Subgroup.mul_mem
    · apply Subgroup.mul_mem
      · exact Subgroup.inv_mem _ (g₁_mem_H 0 0 0)
      · exact Subgroup.inv_mem _ (g₃_mem_H 0 0 0)
    · exact g₁_mem_H 0 0 0
  · exact g₃_mem_H 0 0 0

/-- The 3-cycle c[0, 4, 5] is in H.
    NOTE: Extracting individual 3-cycles from a product of disjoint 3-cycles
    requires Lemma09's technique: combining commutators and squaring.
    This is Phase 3 work - see Lemma09 for the extraction method. -/
theorem first_3cycle_g₁g₃_mem_H : first_3cycle_g₁g₃ ∈ H 0 0 0 := by
  sorry -- Phase 3: requires Lemma09 extraction method

/-- The 3-cycle c[1, 2, 3] is in H.
    NOTE: See first_3cycle_g₁g₃_mem_H for explanation. -/
theorem second_3cycle_g₁g₃_mem_H : second_3cycle_g₁g₃ ∈ H 0 0 0 := by
  sorry -- Phase 3: requires Lemma09 extraction method
